### ISSUE TITLE
Error message, project list

### ISSUE THREAD

**Issue by AKoschella** [carcam/jresearch#17]
Dear all, jresearch works fine except one issue regarding the project list (it worked well in the previous version).
I am using version 3.2.0 Stable
PHP-Version | 5.6.32
Webserver | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/5.6.32 mod_python/3.5.0- Python/2.7.5 mod_wsgi/3.4
Joomla!-Version | Joomla! 3.8.1 Stable [ Amani ] 4-October-2017 14:00 GMT
Joomla!-Plattform-Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

I can access the projects in the backend. However, this error message occurs if I am trying to save the data: 1054 Unknown column 'leaders' in 'field list' 
Unfortunately I am not familiar with MySQL etc...

The projects are correctly displayed in the frontend and links to people involved are correct.

Hopefully you can help. Thanks a lot in advance.
With best regards
Andreas

**Comment by carcam** [comment]
Hi Andreas, it seems like your database structure was not updated with the install. Let's see if @lgalarra can give you a hand on this ;)

**Comment by lgalarra** [comment]
Hi Andreas,

May I ask how did you install J!Research 3.2? Was it via a clean install or update? Which version did you have before? If it was J!Research < 3.1 then you should be able to solve the issue by running in your database the following command:

ALTER TABLE `#__jresearch_project` ADD COLUMN `leaders` TEXT

where #_ should be replaced by the prefix selected at installation time. This should not hurt the component since the column did not exist before.

Best,
Luis

**Comment by AKoschella** [comment]
Dear Luis,

we were in contact many times... I started with version 2.x, which was then updated to 3.0 and later to 3.1. However, I had to migrate from Joomla 2 to Joomla 3. However, I can't remember how I dealt with the jresearch issue there.
Please let me know how to proceed: Doing the ALTER TABLE command or something else.

Thanks a lot. Regards
Andreas

**Comment by lgalarra** [comment]
Hi Andreas, 

Then running the command I mentioned should do the trick. Let me know the outcome.

Cheers,
Luis

**Comment by AKoschella** [comment]
Dear Luis,

it works. Thanks a lot.
Regards,
Andreas

**Comment by lgalarra** [comment]
Great!
